### PR TITLE
Heroku deploy fixes!

### PR DESCRIPTION
**Pull request by ghost**
Why using coffeehouse? It's dead..

### CODE REVIEW

**Comment by aryazakaria01** [comment]
Are you sure this will be fixed ?

**Comment by ghost** [comment]
> Are you sure this will be fixed ?

I've deployed on heroku before pull request.

**Comment by Toni880** [comment]
@Snehashish06 I'm very busy, and haven't had time to update this repo

**Comment by ghost** [comment]
@Toni880 That's why i created pull request in the hope that it would be helpful.

**Pull request closed without merging**
